// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// IDGeneratorClient is the client API for IDGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IDGeneratorClient interface {
	Get(ctx context.Context, in *IDGeneratorRequest, opts ...grpc.CallOption) (*IDGeneratorResponse, error)
}

type iDGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewIDGeneratorClient(cc grpc.ClientConnInterface) IDGeneratorClient {
	return &iDGeneratorClient{cc}
}

func (c *iDGeneratorClient) Get(ctx context.Context, in *IDGeneratorRequest, opts ...grpc.CallOption) (*IDGeneratorResponse, error) {
	out := new(IDGeneratorResponse)
	err := c.cc.Invoke(ctx, "/pb.IDGenerator/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDGeneratorServer is the server API for IDGenerator service.
// All implementations must embed UnimplementedIDGeneratorServer
// for forward compatibility
type IDGeneratorServer interface {
	Get(context.Context, *IDGeneratorRequest) (*IDGeneratorResponse, error)
	mustEmbedUnimplementedIDGeneratorServer()
}

// UnimplementedIDGeneratorServer must be embedded to have forward compatible implementations.
type UnimplementedIDGeneratorServer struct {
}

func (UnimplementedIDGeneratorServer) Get(context.Context, *IDGeneratorRequest) (*IDGeneratorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedIDGeneratorServer) mustEmbedUnimplementedIDGeneratorServer() {}

// UnsafeIDGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDGeneratorServer will
// result in compilation errors.
type UnsafeIDGeneratorServer interface {
	mustEmbedUnimplementedIDGeneratorServer()
}

func RegisterIDGeneratorServer(s grpc.ServiceRegistrar, srv IDGeneratorServer) {
	s.RegisterService(&_IDGenerator_serviceDesc, srv)
}

func _IDGenerator_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDGeneratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDGeneratorServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.IDGenerator/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDGeneratorServer).Get(ctx, req.(*IDGeneratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IDGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.IDGenerator",
	HandlerType: (*IDGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _IDGenerator_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idgenerator.proto",
}
