// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: idgenerator.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IDGeneratorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *IDGeneratorRequest) Reset() {
	*x = IDGeneratorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idgenerator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDGeneratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDGeneratorRequest) ProtoMessage() {}

func (x *IDGeneratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idgenerator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDGeneratorRequest.ProtoReflect.Descriptor instead.
func (*IDGeneratorRequest) Descriptor() ([]byte, []int) {
	return file_idgenerator_proto_rawDescGZIP(), []int{0}
}

func (x *IDGeneratorRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type IDGeneratorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IDGeneratorResponse) Reset() {
	*x = IDGeneratorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idgenerator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDGeneratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDGeneratorResponse) ProtoMessage() {}

func (x *IDGeneratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idgenerator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDGeneratorResponse.ProtoReflect.Descriptor instead.
func (*IDGeneratorResponse) Descriptor() ([]byte, []int) {
	return file_idgenerator_proto_rawDescGZIP(), []int{1}
}

func (x *IDGeneratorResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *IDGeneratorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_idgenerator_proto protoreflect.FileDescriptor

var file_idgenerator_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2e, 0x0a, 0x12, 0x49, 0x44, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x13, 0x49, 0x44, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x47, 0x0a, 0x0b, 0x49, 0x44, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x38, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x16,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x44, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x44, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idgenerator_proto_rawDescOnce sync.Once
	file_idgenerator_proto_rawDescData = file_idgenerator_proto_rawDesc
)

func file_idgenerator_proto_rawDescGZIP() []byte {
	file_idgenerator_proto_rawDescOnce.Do(func() {
		file_idgenerator_proto_rawDescData = protoimpl.X.CompressGZIP(file_idgenerator_proto_rawDescData)
	})
	return file_idgenerator_proto_rawDescData
}

var file_idgenerator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idgenerator_proto_goTypes = []interface{}{
	(*IDGeneratorRequest)(nil),  // 0: pb.IDGeneratorRequest
	(*IDGeneratorResponse)(nil), // 1: pb.IDGeneratorResponse
}
var file_idgenerator_proto_depIdxs = []int32{
	0, // 0: pb.IDGenerator.Get:input_type -> pb.IDGeneratorRequest
	1, // 1: pb.IDGenerator.Get:output_type -> pb.IDGeneratorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idgenerator_proto_init() }
func file_idgenerator_proto_init() {
	if File_idgenerator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idgenerator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDGeneratorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idgenerator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDGeneratorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idgenerator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idgenerator_proto_goTypes,
		DependencyIndexes: file_idgenerator_proto_depIdxs,
		MessageInfos:      file_idgenerator_proto_msgTypes,
	}.Build()
	File_idgenerator_proto = out.File
	file_idgenerator_proto_rawDesc = nil
	file_idgenerator_proto_goTypes = nil
	file_idgenerator_proto_depIdxs = nil
}
